### ISSUE TITLE
Sidekiq 5.0 meta-issue

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3301]
Happy 2017! 🍰 🎉 

Sidekiq 5.0 should be available in ~~February~~ April.

* [x] [Redesign dispatch for Rails 5](/mperham/sidekiq/issues/3235)
* [x] [Don't load delay extensions by default](/mperham/sidekiq/issues/3299)
* [x] Use [TSTP for quiet signal](/mperham/sidekiq/issues/3302) going forward
* [x] Update supported Ruby and Rails versions
* [x] [Make Web UI RTL-friendly](/mperham/sidekiq/issues/3381)
* [x] Graceful handling of malformed job payloads

[Release notes here](/mperham/sidekiq/blob/5-0/5.0-Upgrade.md).

Other ideas?  Questions?  Chime in.

**Comment by Nowaker** [comment]
`.delay` gone, good riddance. I still remember several hours lost because `sidekiq_options` didn't work there. :+1:

**Comment by mperham** [comment]
@Nowaker sidekiq_options doesn't work but the delay methods accept hashes so you can do stuff like:

```ruby
Foo.delay(retry: 3).bar(args...)
```

**Comment by mperham** [comment]
The 5-0 branch is feature complete now.  You can test it like so:

```ruby
gem 'sidekiq', github: 'mperham/sidekiq', branch: '5-0'
```

**Comment by Nowaker** [comment]
@mperham I know. I'm just mentioning #2494 - I lost hours on `sidekiq_options` inside `.delay`. :cry:

**Comment by mperham** [comment]
5.0 beta 2 has been released, use it like so:

```ruby
gem 'sidekiq', '5.0.0.beta2'
```

Read the release notes if something doesn't work!

**Comment by Mysrt** [comment]
When using rails 5 with either the sidekiq 4.x or 5.x anytime a sidekiq job failed the args would not be recorded and therefore the job couldn't really be retried.  My method signatures were pretty bland.  I will include what I can.  After investigation what seemed like what was happening is 'args' were being specified twice when the item was being re-enqueued.  The second time it was specified was an empty array which overwrite the correct args specification.

Here is the failure output from STDOUT, you can see 'args' is specified two times.  One time with the correct arguments to retry with, and then a second time with blank arguments.

`WARN: {"context":"Job raised exception","job":{"class":"ItemCreationService","args":
[{"name":"Charles Xavier","item_number":"7732432"}],"retry":true,"queue":"default","jid":"d8f6a3c8b1833bcec333eee6","created_at":1490893455.669237,"bid":"QLJ0VmH-4icGzw","enqueued_at":1490893455.669457,"args":[],"error_message":"","error_class":"RuntimeError","failed_at":1490893455.6851652,"retry_count":0},"jobstr":"{\"class\":\"ItemCreationService\",\"args\":[{\"name\":\"Charles Xavier\",\"item_number\":\"7774567890\"}],\"retry\":true,\"queue\":\"default\",\"jid\":\"d8f6a3c8b1833bcec333eee6\",\"created_at\":1490893455.669237,\"bid\":\"QLJ0VmH-4icGzw\",\"enqueued_at\":1490893455.669457}"}`

Here are snippets from both my enqueuing service and the worker.

          require 'csv'

          class BatchUploader < ActiveRecord::Base

            #called on successful batch upload
            def on_success(status, params)
              batch = BatchUploader.find_by_batch_id(params["bid"])
              batch.update_attributes(successful: true)
            end

            def self.create_batch(client_key, file)
              batch = Sidekiq::Batch.new
              batch.description = "NPI upload for user #{client_key}"
              batch.on(:success, BatchUploader, 'bid' => batch.bid)

              batch.jobs do
                csv = CSV.read(file.path)
                csv.shift # remove header row
                csv.each do |csv_row|
                  #args = {"name" => row[0], "item_number" => row[1]}
                  ItemCreationService.perform_async(csv_row[0].to_s, csv_row[1].to_s)
                end
              end
              BatchUploader.create!(client_key: client_key, batch_id: batch.bid, filename: file.original_filename)
            end

          end

          class ItemCreationService
            include Sidekiq::Worker
            sidekiq_options retry: 5

            def perform(name, item_number)
              #send off ot the service
              #sleep 5
              raise StandardError.new("failure creating")  if rand(100) < 50

            end
          end

Wasn't sure if this belonged in it's own issue or not/ If you already knew about it but felt I should mention it somewhere.  I can try to create a demo-app for this bug if you are unable to reproduce.

**Comment by mperham** [comment]
@Mysrt If this is happening on Sidekiq 4 and 5, then please open a separate issue.  A reproducible script would help tremendously.

**Comment by Mysrt** [comment]
spent time investigating and was unable to reproduce in a fresh app.  Then I upgraded the failing app back to rails 5 and It works now on rails 5.  I think it may have been some odd configuration choices or gem conflicts.  I'll keep investigating and see if i can get steps to reproduce

**Comment by mperham** [comment]
5-0 will be merged on Friday.  If you are riding on master today, you should test 5-0 out.

**Comment by mperham** [comment]
master is now 5.0.  Branch `4.x` created to handle backported fixes.

🍰 🎆
